name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: stop the server
        run: docker-compose down
      - name: delete existing image
        run: docker rmi -f teamwork
      - name: start the server again
        run: docker-compose up -d
